apiVersion: v2
name: nanomon
description: Deploy NanoMon, a HTTP and network monitoring tool
type: application
version: "0.0.10"
appVersion: "0.2.2"
dependencies:
  - name: postgresql
    version: "18.3.0"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
