root = "."
tmp_dir = "tmp"

[build]
include_ext = ["go"]
include_dir = [
  "services/runner",
  "services/common/database",
  "services/common/monitor",
  "services/common/result",
]
cmd = "go build -o ./tmp/runner nanomon/services/runner"
bin = "tmp/runner"

[misc]
clean_on_exit = true
