apiVersion: apps/v1
kind: Deployment
metadata:
  name: nanomon-api
spec:
  selector:
    matchLabels:
      app: nanomon-api
  template:
    metadata:
      labels:
        app: nanomon-api
    spec:
      containers:
        - name: nanomon-api
          image: ghcr.io/benc-uk/nanomon-api:dev
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          env:
            - name: POSTGRES_DSN
              value: "host=postgres port=5432 user=nanomon dbname=nanomon sslmode=disable"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password

          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: nanomon-api
spec:
  type: LoadBalancer
  selector:
    app: nanomon-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
