{{- if .Values.runner.alerting.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nanomon.fullname" . }}-alerting
type: Opaque
data: 
  smtpPassword: {{ .Values.runner.alerting.password | b64enc | quote }}
{{- end -}}
