apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nanomon.fullname" . }}-frontend
  labels:
    {{- include "nanomon.labels" . | nindent 4 }}
    component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "nanomon.selectorLabels" . | nindent 6 }}
      component: frontend
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nanomon.selectorLabels" . | nindent 8 }}
        component: frontend
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.regRepo }}/nanomon-frontend:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
          ports:
            - name: http
              containerPort: 8001
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
          - name: API_ENDPOINT
            {{- if .Values.frontend.apiEndpoint }}
            value: {{ .Values.frontend.apiEndpoint }}
            {{- else }}
            value: /api
            {{- end }}
            {{- if .Values.authClientId }}
          - name: AUTH_CLIENT_ID
            value: {{ .Values.authClientId }}
            {{- end }}
            {{- if .Values.authTenant }}
          - name: AUTH_TENANT
            value: {{ .Values.authTenant }}
            {{- end }}     
          {{- range $key, $value := .Values.frontend.extraEnvs }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}                       
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
