{{- if .Values.postgresql.externalPassword -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql
type: Opaque
data: 
  password: {{ .Values.postgresql.externalPassword | b64enc | quote }}
{{- end -}}
