@endpoint = http://localhost:8000

// Token 
@jwt = THIS_IS_IGNORED.eyJwcmVmZXJyZWRfdXNlcm5hbWUiOiJiZWNvbGVtQG1pY3Jvc29mdC5jb20ifQ.THIS_IS_IGNORED

### Get all monitors
GET {{endpoint}}/monitors

### Create a monitor
POST {{endpoint}}/monitors
Authorization: Bearer {{ jwt }}
Content-Type: application/json

{
  "name": "Test {{$randomInt 1 1000}}",
  "type": "http",
  "interval": "10s",
  "enabled": true,
  "properties": {
    "url": "http://example.net"
  }
}

### Get single monitor
GET {{endpoint}}/monitors/6416d530c963a60b42dcf8d6

### Delete single monitor
DELETE {{endpoint}}/monitors/64170494109c886d716ca7b8
Authorization: Bearer {{ jwt }}

### Get results
GET {{endpoint}}/monitors/641716bfcd41146100d341f3/results?max=2

### Update a monitor
PUT {{endpoint}}/monitors/641b26191394844e49c86467
Authorization: Bearer {{ jwt }}
Content-Type: application/json

{
  "name": "AAAABBBB",
  "type": "http",
  "interval": "1110s",
  "enabled": false,
  "properties": {
    "url": "http://examplezzzz.net",
    "blah": "some words"
  }
}
