@endpoint = http://localhost:8000

##########################################
### Get all monitors
##########################################
GET {{endpoint}}/monitors

##########################################
### Create a monitor
##########################################
POST {{endpoint}}/monitors
Content-Type: application/json

{
  "name": "Test {{$randomInt 1 1000}}",
  "type": "http",
  "interval": "10s",
  "target": "http://192.168.0.100/",
  "enabled": true
}

##########################################
### Get single monitor
##########################################
GET {{endpoint}}/monitors/641f75c9062e612df8596c70

##########################################
### Delete single monitor
##########################################
DELETE {{endpoint}}/monitors/641fdbfb1717fb28657215ad

##########################################
### Get results
##########################################
GET {{endpoint}}/monitors/641f6415bcb6e797bdabdade/results?max=200

##########################################
### Update a monitor
##########################################
PUT {{endpoint}}/monitors/641f7415062e612df8596c6f
Content-Type: application/json

{
  "name": "Check Router",
  "type": "tcp",
  "interval": "10s",
  "enabled": true,
  "target": "192.168.0.1:802",
  "rule": "respTime < 1"
}

##########################################
### Get results for ALL monitors
##########################################
GET {{endpoint}}/results?max=10
