apiVersion: v1
entries:
  nanomon:
  - apiVersion: v2
    appVersion: 0.2.0
    created: "2025-07-20T22:07:29.311668161+01:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 16.7.20
    description: Deploy NanoMon, a HTTP and network monitoring tool
    digest: 2a47f0492dac0502ac877463c1bebfe171224445a9bc2f4da1ceddba31df9e40
    name: nanomon
    type: application
    urls:
    - nanomon-0.0.8.tgz
    version: 0.0.8
  - apiVersion: v2
    appVersion: 0.1.3
    created: "2025-07-20T22:07:29.298994937+01:00"
    dependencies:
    - condition: mongodb.enabled
      name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 13.x.x
    description: Deploy NanoMon, a HTTP and network monitoring tool
    digest: 5f2714b99252cd0234a1f6fc8d11f03d4297edaecfee96e999853844ebcc1f90
    name: nanomon
    type: application
    urls:
    - nanomon-0.0.7.tgz
    version: 0.0.7
  - apiVersion: v2
    appVersion: 0.1.3
    created: "2025-07-20T22:07:29.288484194+01:00"
    dependencies:
    - condition: mongodb.enabled
      name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 13.x.x
    description: Deploy NanoMon, a HTTP and network monitoring tool
    digest: 7813ba9d4443268cf60826887c974ae0c3a81202b6e1b6ea7a8fd40115e65de9
    name: nanomon
    type: application
    urls:
    - nanomon-0.0.6.tgz
    version: 0.0.6
  - apiVersion: v2
    appVersion: 0.0.4
    created: "2025-07-20T22:07:29.274612065+01:00"
    dependencies:
    - condition: mongodb.enabled
      name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 13.x.x
    description: Deploy NanoMon, a HTTP and network monitoring tool
    digest: 548017dc70b65e20f85b8b231a52c8c7d67c6da231c1e413bc05d2ad95c43d6f
    name: nanomon
    type: application
    urls:
    - nanomon-0.0.5.tgz
    version: 0.0.5
  - apiVersion: v2
    appVersion: 0.0.3
    created: "2025-07-20T22:07:29.257286201+01:00"
    dependencies:
    - condition: mongodb.enabled
      name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 13.x.x
    description: Deploy NanoMon, a HTTP and network monitoring tool
    digest: 0b4e8fc35089d0bd7a327fcbb13c12d61a82fe5fe14e8bbf828cfb64826c9241
    name: nanomon
    type: application
    urls:
    - nanomon-0.0.4.tgz
    version: 0.0.4
generated: "2025-07-20T22:07:29.247046645+01:00"
