apiVersion: apps/v1
kind: Deployment
metadata:
  name: nanomon-runner
spec:
  selector:
    matchLabels:
      app: nanomon-runner
  template:
    metadata:
      labels:
        app: nanomon-runner
    spec:
      containers:
        - name: nanomon-runner
          image: ghcr.io/benc-uk/nanomon-runner:dev
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          env:
            - name: POSTGRES_DSN
              value: "host=postgres port=5432 user=nanomon dbname=nanomon sslmode=disable"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
