@endpoint = http://localhost:8000/api

##########################################
### Get all monitors
##########################################
GET {{endpoint}}/monitors


##########################################
### Create a monitor
##########################################
# @name create
POST {{endpoint}}/monitors
Content-Type: application/json

{
  "name": "Test {{$randomInt 1 1000}}",
  "type": "http",
  "interval": "1s",
  "target": "http://localhost:8000",
  "enabled": true,
  "group": "test"
}


##########################################
### Get single monitor
##########################################
GET {{endpoint}}/monitors/{{ create.response.body.id }}


##########################################
### Delete single monitor
##########################################
DELETE {{endpoint}}/monitors/{{ create.response.body.id }}


##########################################
### Get results
##########################################
GET {{endpoint}}/monitors/{{ create.response.body.id }}/results?max=5


##########################################
### Update a monitor
##########################################
PUT {{endpoint}}/monitors/{{ create.response.body.id }}
Content-Type: application/json

{
  "name": "Test {{$randomInt 1 1000}}",
  "type": "http",
  "interval": "10s",
  "target": "http://localhost:8000",
  "enabled": true
}


##########################################
### Get results for ALL monitors
##########################################
GET {{endpoint}}/results?max=10


##########################################
### Test import
##########################################
POST {{endpoint}}/monitors/import
Content-Type: application/json

[
  {
    "name": "Test Health",
    "type": "http",
    "interval": "20s",
    "target": "http://localhost:8000/health",
    "enabled": true
  },
  {
    "name": "Test Status",
    "type": "http",
    "interval": "5s",
    "target": "http://localhost:8000/status",
    "enabled": true
  }
]